copying from 8.0 branch beacause
$ git log refs/heads/8.0-extract --since=2015-10-14 --pretty=format:'%H' --reverse | while read line || [ -n "$line" ] ; do
>   git cherry-pick $line
> done
error: Commit 698d7875cc5e3145a59a07bd3b1b3d40cf81822e is a merge but no -m option was given.
fatal: cherry-pick failed
[9.0-stock_picking_invoice_link fd53a50] OCA Transbot updated translations from Transifex
 Author: OCA Transbot <transbot@odoo-community.org>
 Date: Mon Oct 26 08:22:09 2015 -0400
 3 files changed, 214 insertions(+)
 create mode 100644 stock_picking_invoice_link/i18n/fr.po
 create mode 100644 stock_picking_invoice_link/i18n/it.po
 create mode 100644 stock_picking_invoice_link/i18n/sl.po
[9.0-stock_picking_invoice_link 9a4358f] OCA Transbot updated translations from Transifex
 Author: OCA Transbot <transbot@odoo-community.org>
 Date: Sun Feb 21 01:45:13 2016 -0500
 1 file changed, 72 insertions(+)
 create mode 100644 stock_picking_invoice_link/i18n/es.po
error: could not apply 1b8d487... [IMP] stock_picking_invoice_link: added new functionality
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
error: cherry-pick is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: cherry-pick failed
error: cherry-pick is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: cherry-pick failed
error: cherry-pick is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: cherry-pick failed
error: cherry-pick is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: cherry-pick failed
error: cherry-pick is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: cherry-pick failed
error: cherry-pick is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: cherry-pick failed
error: cherry-pick is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: cherry-pick failed
error: cherry-pick is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: cherry-pick failed
error: cherry-pick is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: cherry-pick failed

Conflicts:
	stock_picking_invoice_link/models/stock_picking.py